use phf_codegen::Map;
use std::{fs::File, io::{BufReader, BufWriter, Write}, path::Path};

fn main() {
	println!("cargo:rerun-if-changed=data/pinyin.csv");

	let out_path = Path::new("src/generated").join("pinyin_map.rs");
	let mut file = BufWriter::new(File::create(&out_path).unwrap());

	let csv_path = Path::new("data/pinyin.csv");
	let reader = BufReader::new(File::open(csv_path).unwrap());
	let mut rdr = csv::Reader::from_reader(reader);

	let mut map = Map::new();

	writeln!(&mut file, "// This file is generated by build.rs. Do not edit manually.\n").unwrap();

	for result in rdr.records().skip(1) {
		let record = result.unwrap();
		let code_str = &record[0];
		let pinyin_vec = &record[1].split("|").map(|s| s.to_string()).collect::<Vec<String>>();
		let character = &record[2].to_string().chars().next().unwrap();
		let code_u32 = u32::from_str_radix(code_str.trim_start_matches("U+"), 16).unwrap();
		let value_str = format!(
			"('{}', &[{}])",
			character,
			pinyin_vec
				.iter()
				.map(|s| format!("\"{}\"", s))
				.collect::<Vec<_>>()
				.join(", ")
		);
		map.entry(
			code_u32,
			value_str.as_str(),
		);
	}

	writeln!(
		&mut file,
		"pub static PINYIN_MAP: ::phf::Map<u32, (char, &'static [&'static str])> = {};\n",
		map.build()
	).unwrap();
}