use phf_codegen::Map;
use std::collections::BTreeSet;
use std::{
    fs::File,
    io::{BufReader, BufWriter, Write},
    path::{Path, PathBuf},
};

fn main() {
    let manifest_dir = match std::env::var("CARGO_MANIFEST_DIR") {
        Ok(dir) => dir,
        Err(_) => fail("CARGO_MANIFEST_DIR is not set"),
    };
    let project_root = Path::new(&manifest_dir);
    let data_dir = project_root.join("data");
    let data_csv = data_dir.join("pinyin.csv");
    let stroke_csv = data_dir.join("strokes.csv");

    // Re-run codegen when the inputs change. `build.rs` itself is included so
    // edits to the generation logic also trigger a rebuild.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", data_csv.display());
    println!("cargo:rerun-if-changed={}", stroke_csv.display());

    let src_dir = project_root.join("src");
    let generated_dir = src_dir.join("generated");
    if let Err(error) = std::fs::create_dir_all(&generated_dir) {
        fail(&format!(
            "failed to create generated dir {}: {error}",
            generated_dir.display()
        ));
    }

    generate_pinyin_map(&data_csv, &generated_dir.join("pinyin_map.rs"));
    generate_stroke_map(&stroke_csv, &generated_dir.join("stroke_map.rs"));
}

fn fail(message: &str) -> ! {
    println!("cargo:warning={message}");
    eprintln!("build.rs: {message}");
    std::process::exit(1);
}

fn open_csv(path: &Path) -> csv::Reader<BufReader<File>> {
    let file = File::open(path).unwrap_or_else(|error| {
        fail(&format!("failed to open {}: {error}", path.display()));
    });
    csv::Reader::from_reader(BufReader::new(file))
}

fn create_output(path: &Path) -> BufWriter<File> {
    let file = File::create(path).unwrap_or_else(|error| {
        fail(&format!(
            "failed to create generated file {}: {error}",
            path.display()
        ));
    });
    BufWriter::new(file)
}

fn parse_codepoint(raw: &str, source: &Path, line: usize) -> u32 {
    let trimmed = raw.trim_start_matches("U+");
    u32::from_str_radix(trimmed, 16).unwrap_or_else(|error| {
        fail(&format!(
            "{}:{line}: invalid codepoint '{raw}': {error}",
            source.display()
        ));
    })
}

fn generate_pinyin_map(data_csv: &Path, out_path: &Path) {
    let mut writer = create_output(out_path);
    let mut rdr = open_csv(data_csv);

    let mut map = Map::new();
    let mut seen_codepoints = BTreeSet::new();
    let source = PathBuf::from(data_csv);

    writeln!(
        &mut writer,
        "// This file is generated by build.rs. Do not edit manually.\n"
    )
    .unwrap_or_else(|error| fail(&format!("failed to write {}: {error}", out_path.display())));

    for (index, result) in rdr.records().enumerate() {
        let line = index + 2; // header + 1-based
        let record = result.unwrap_or_else(|error| {
            fail(&format!(
                "{}:{line}: failed to read CSV row: {error}",
                source.display()
            ));
        });
        if record.len() != 3 {
            fail(&format!(
                "{}:{line}: expected exactly 3 columns (codepoint, pinyin, char), got {}",
                source.display(),
                record.len()
            ));
        }

        let code_str = &record[0];
        let pinyins_field = &record[1];
        let char_field = &record[2];

        let code_u32 = parse_codepoint(code_str, &source, line);

        let mut chars_iter = char_field.chars();
        let character = chars_iter.next().unwrap_or_else(|| {
            fail(&format!(
                "{}:{line}: empty character column for {code_str}",
                source.display()
            ))
        });
        if chars_iter.next().is_some() {
            fail(&format!(
                "{}:{line}: character column must contain exactly one Unicode scalar (got {char_field:?})",
                source.display()
            ));
        }
        if character as u32 != code_u32 {
            fail(&format!(
                "{}:{line}: character {character:?} does not match codepoint {code_str}",
                source.display()
            ));
        }

        let pinyin_vec: Vec<&str> = pinyins_field.split('|').collect();
        if pinyin_vec.iter().any(|s| s.is_empty()) {
            fail(&format!(
                "{}:{line}: empty pinyin entry for {code_str} ({pinyins_field:?})",
                source.display()
            ));
        }

        // The primary pinyin (first reading) is what powers the fast u128
        // sort-key encoding via `encode_primary_pinyin_unchecked`. Enforce its
        // invariants at build time so the unchecked path is safe by
        // construction. Alternate readings can be non-ASCII (e.g. `ê1`) since
        // they are only exposed via `pinyin_of`, never encoded.
        let primary = pinyin_vec[0];
        if !primary.is_ascii() {
            fail(&format!(
                "{}:{line}: primary pinyin {primary:?} for {code_str} must be ASCII; \
                 normalize ü to v in the data pipeline",
                source.display()
            ));
        }
        if primary.len() > 16 {
            fail(&format!(
                "{}:{line}: primary pinyin {primary:?} for {code_str} exceeds 16 bytes",
                source.display()
            ));
        }

        seen_codepoints.insert(code_u32);
        let value_str = format!(
            "('{}', &[{}])",
            character,
            pinyin_vec
                .iter()
                .map(|s| format!("\"{s}\""))
                .collect::<Vec<_>>()
                .join(", ")
        );
        map.entry(code_u32, value_str.as_str());
    }

    writeln!(
        &mut writer,
        "pub static PINYIN_MAP: ::phf::Map<u32, (char, &'static [&'static str])> = {};\n",
        map.build()
    )
    .unwrap_or_else(|error| fail(&format!("failed to write {}: {error}", out_path.display())));

    for required in [0x3007_u32, 0x6C49, 0x91CD] {
        if !seen_codepoints.contains(&required) {
            fail(&format!(
                "required codepoint U+{required:04X} is missing from generated pinyin data; \
                 regenerate {} from the upstream pinyin dataset",
                source.display()
            ));
        }
    }
}

fn generate_stroke_map(data_csv: &Path, out_path: &Path) {
    let mut writer = create_output(out_path);
    let mut rdr = open_csv(data_csv);

    let mut map = Map::new();
    let mut seen_codepoints = BTreeSet::new();
    let source = PathBuf::from(data_csv);

    writeln!(
        &mut writer,
        "// This file is generated by build.rs. Do not edit manually.\n"
    )
    .unwrap_or_else(|error| fail(&format!("failed to write {}: {error}", out_path.display())));

    for (index, result) in rdr.records().enumerate() {
        let line = index + 2;
        let record = result.unwrap_or_else(|error| {
            fail(&format!(
                "{}:{line}: failed to read CSV row: {error}",
                source.display()
            ));
        });
        // The strokes CSV currently has 3 columns (codepoint, strokes, char)
        // but we only need the first two. Allow either 2 or 3 to keep the
        // pipeline forgiving while still rejecting wildly malformed rows.
        if record.len() < 2 || record.len() > 3 {
            fail(&format!(
                "{}:{line}: expected 2 or 3 columns (codepoint, strokes[, char]), got {}",
                source.display(),
                record.len()
            ));
        }

        let code_str = &record[0];
        let stroke_str = &record[1];
        let code_u32 = parse_codepoint(code_str, &source, line);
        let stroke_count: u16 = stroke_str.parse().unwrap_or_else(|error| {
            fail(&format!(
                "{}:{line}: invalid stroke count '{stroke_str}' for {code_str}: {error}",
                source.display()
            ));
        });
        if stroke_count == 0 {
            fail(&format!(
                "{}:{line}: stroke count must be greater than 0 for {code_str}",
                source.display()
            ));
        }
        seen_codepoints.insert(code_u32);
        map.entry(code_u32, &stroke_count.to_string());
    }

    writeln!(
        &mut writer,
        "pub static STROKE_MAP: ::phf::Map<u32, u16> = {};\n",
        map.build()
    )
    .unwrap_or_else(|error| fail(&format!("failed to write {}: {error}", out_path.display())));

    for required in [0x4E00_u32, 0x6C49, 0x91CD] {
        if !seen_codepoints.contains(&required) {
            fail(&format!(
                "required codepoint U+{required:04X} is missing from generated stroke data; \
                 regenerate {} from the upstream Unihan dataset",
                source.display()
            ));
        }
    }
}
