use phf_codegen::Map;
use std::collections::BTreeSet;
use std::{
    fs::File,
    io::{BufReader, BufWriter, Write},
    path::Path,
};

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let project_root = Path::new(&manifest_dir);
    let data_dir = project_root.join("data");
    let data_csv = data_dir.join("pinyin.csv");
    let stroke_csv = data_dir.join("strokes.csv");
    println!("cargo:rerun-if-changed={}", data_csv.display());
    println!("cargo:rerun-if-changed={}", stroke_csv.display());

    let src_dir = project_root.join("src");
    let generated_dir = src_dir.join("generated");
    generate_pinyin_map(&data_csv, &generated_dir.join("pinyin_map.rs"));
    generate_stroke_map(&stroke_csv, &generated_dir.join("stroke_map.rs"));
}

fn generate_pinyin_map(data_csv: &Path, out_path: &Path) {
    let mut file = BufWriter::new(File::create(out_path).unwrap());
    let reader = BufReader::new(File::open(data_csv).unwrap());
    let mut rdr = csv::Reader::from_reader(reader);

    let mut map = Map::new();
    let mut seen_codepoints = BTreeSet::new();

    writeln!(
        &mut file,
        "// This file is generated by build.rs. Do not edit manually.\n"
    )
    .unwrap();

    for result in rdr.records() {
        let record = result.unwrap();
        let code_str = &record[0];
        let pinyin_vec = &record[1]
            .split("|")
            .map(|s| s.to_string())
            .collect::<Vec<String>>();
        let character = &record[2].to_string().chars().next().unwrap();
        let code_u32 = u32::from_str_radix(code_str.trim_start_matches("U+"), 16).unwrap();
        seen_codepoints.insert(code_u32);
        let value_str = format!(
            "('{}', &[{}])",
            character,
            pinyin_vec
                .iter()
                .map(|s| format!("\"{}\"", s))
                .collect::<Vec<_>>()
                .join(", ")
        );
        map.entry(code_u32, value_str.as_str());
    }

    writeln!(
        &mut file,
        "pub static PINYIN_MAP: ::phf::Map<u32, (char, &'static [&'static str])> = {};\n",
        map.build()
    )
    .unwrap();

    for required in [0x3007_u32, 0x6C49, 0x91CD] {
        assert!(
            seen_codepoints.contains(&required),
            "required codepoint U+{required:04X} is missing from generated pinyin data"
        );
    }
}

fn generate_stroke_map(data_csv: &Path, out_path: &Path) {
    let mut file = BufWriter::new(File::create(out_path).unwrap());
    let reader = BufReader::new(File::open(data_csv).unwrap());
    let mut rdr = csv::Reader::from_reader(reader);

    let mut map = Map::new();
    let mut seen_codepoints = BTreeSet::new();

    writeln!(
        &mut file,
        "// This file is generated by build.rs. Do not edit manually.\n"
    )
    .unwrap();

    for result in rdr.records() {
        let record = result.unwrap();
        let code_str = &record[0];
        let stroke_count: u16 = record[1].parse().unwrap();
        let code_u32 = u32::from_str_radix(code_str.trim_start_matches("U+"), 16).unwrap();
        seen_codepoints.insert(code_u32);
        map.entry(code_u32, &stroke_count.to_string());
    }

    writeln!(
        &mut file,
        "pub static STROKE_MAP: ::phf::Map<u32, u16> = {};\n",
        map.build()
    )
    .unwrap();

    for required in [0x4E00_u32, 0x6C49, 0x91CD] {
        assert!(
            seen_codepoints.contains(&required),
            "required codepoint U+{required:04X} is missing from generated stroke data"
        );
    }
}
